### ISSUE TITLE
Chromebook support

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyPropClient#12]
This might be very important since some schools will have Chromebooks that students use.

**Comment by zfi** [comment]
Chromebooks have some interesting requirements in order to talk with the embedded hardware. I am looking at this now.

**Comment by PropGit** [comment]
Closing.  We've implemented Chromebook support via a new project: [BlocklyProp Launcher](BlocklyPropClient_Web).
