### ISSUE TITLE
Research is python able to be used on a chrome book?

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyPropClient#13]
Is it possible to use Python on a ChromeBook? If not, is there a substitute that we can use?

**Comment by PropGit** [comment]
I don't know the answer to that; however, our Chrome developers ( see https://github.com/parallaxinc/ChromeIDE ) may be able to assist in converting this to a form suitable for ChromeBooks.  The same result may also support the other platforms as well.  We've already posed the idea to them of making the same framework support BlocklyProp functionality in some sort of absorbed way, but it's too early to start focusing on that yet until we get BASIC Stamp and Propeller support implemented well in our Chrome IDE.

**Comment by DarkmatterVale** [comment]
Ok. I believe we will definitely need some help because after some looking, Python is not natively able to run on Chromebooks. This will mean we will probably need to find some other way to run the application. Luckily though, once the Propeller is able to work in ChromeIDE we should be able to take a lot of the work there and apply it to our situation.

**Comment by DarkmatterVale** [comment]
This probably won't work out. I am going to close this issue because it is not currently relevant.
