### ISSUE TITLE
GCC on Mac

### ISSUE THREAD

**Issue by DarkmatterVale** [parallaxinc/BlocklyPropClient#18]
This needs a solution since it is currently breaks compiling code on the client.

Are we going to add the PropellerGCC toolchain to the client? What solution do we have in mind?

**Comment by michel-cf** [comment]
Our current line of thinking is:

once the server has been moved to java, we'll provide a service that can handle compilation on the server. For those wanting to do offline compilation, I'll add a button to download the GCC toolchain from within the client. Automatically installing it into its own directories. (A download version with the gcc toolchain included will also be made available for those without access to the internet from the computer they want to run it on)

In the near future I'll make a diagram of all possible combinations of online and offline hosting and compiling.

**Comment by DarkmatterVale** [comment]
That sounds like a great way to handle compilation.

**Comment by michel-cf** [comment]
Not applicable anymore since we have the Cloud-compiler
