### ISSUE TITLE
Create Installer

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyPropClient#24]
Create installer for the client that installs on each supported platform and also includes the FTDI drivers (if necessary).

Current Supported Platforms
- Windows 7/8/8.1/10 - 64-bit
- Mac OSX 64-bit

**Comment by DarkmatterVale** [comment]
Has this been completed? It sounds like a necessary thing to have before public launch...

**Comment by zfi** [comment]
The new installers for Windows and OS X have been deployed to the Demo site. I have used the Windows installer once and that was successful.

**Comment by PropGit** [comment]
I will close this issue now, although we'll continue to update the installers as need be after this moment.
