### ISSUE TITLE
Add error processing for download-but-nothing-happens condition

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyPropClient#32]
Today Jim found code that seems to be directly involved with the download-successful-but-nothing-happens condition reported on occasion by some customers.

Add exception handling and error processing to this code.

If possible now, add a fix to prevent the erroneous condition in the first place.

**Comment by zfi** [comment]
The loader code would occasionally throw an uncaught exception after downloading the .elf file from the Cloud Session server. The UI would report that the code was successfully downloaded but it would never complete the messages that would normally appear after the target device was programmed.

The latest code (0.5.1) traps these errors and reports it back up the stack. We still need an update to the UI to report this to the user.

**Comment by PropGit** [comment]
Created Issue #53 for UI portion of this task.  Logging it working; closing this issue now.
