### ISSUE TITLE
Add logging feature so we can find problems at customer installations

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyPropClient#35]
Add logging feature to client so we can research deep problems that occur at customer installations.

Some (or all) of this is already in-place as of today; but work continues.

**Comment by zfi** [comment]
This is partially addressed in PR #36. Detailed FTDI state is available for debian linux systems. The new client will write application status to a disk file. The fire is overwritten at client startup if it exists.

**Comment by zfi** [comment]
Fixed in PR #41

**Comment by PropGit** [comment]
This is now addressed for Linux, Mac, and Windows.  @PropGit verified on Windows and Mac.

**Comment by PropGit** [comment]
Closing issue.  Further logging enhancements will be documented by future issues.
