### ISSUE TITLE
Version Number Management

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/BlocklyPropClient#73]
@zfi 

From [this commit](https://github.com/parallaxinc/BlocklyPropClient/commit/c0e009fab0d573e419ec534d6dbfaae7a8a2483d) it appears that the version number is currently stored in three different places:

- BlocklyPropClient.py
- about.txt
- package/blocklypropclient-installer.iss

and with the recent enhancement of the Mac build/sign/packaging spec and scripts, it is also necessary for it to be placed in the Info.plist's CFBundleShortVersionString element (currently done automatically at signing/packaging time).

Until/unless we have a way to manage this better in the future, I think I should add a small _sed_ script to the repo that will adjust the version in each of the necessary places in one step- something we can use like this, for example:
```
  $ set_version 0.5.3
```

Do you agree with all of this, above?

**Comment by PropGit** [comment]
I did this in PR #74.  I'll do some final testing/review before merging and closing this issue.

**Comment by zfi** [comment]
It looks like PR#74 includes a script that tags a number of files with a specific version number. I'm looking at this from an automated build process. Which file tracks the current version number?

**Comment by PropGit** [comment]
@zfi - Not sure I understand the question.  If you're asking which file an automated build process should check for an "official" version number, I'd say it's BlocklyPropClient.py.
